
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 21 23:42:46 CST 2019
//----------------------------------------------------

package Analizadores.GramaticaFS;

/** CUP generated class containing symbol constants. */
public class simbolofs {
  /* terminals */
  public static final int igualigual = 16;
  public static final int maximo = 32;
  public static final int imprimir = 40;
  public static final int mayorq = 12;
  public static final int alguno = 39;
  public static final int valor_path = 51;
  public static final int detener = 45;
  public static final int coma = 21;
  public static final int igual = 6;
  public static final int valor_numero_completo = 50;
  public static final int valor_id = 49;
  public static final int reduce = 37;
  public static final int llavec = 5;
  public static final int ascendente = 30;
  public static final int llavea = 4;
  public static final int si = 42;
  public static final int valor_falso = 55;
  public static final int importar = 41;
  public static final int parenc = 3;
  public static final int defecto = 48;
  public static final int valor_verdadero = 54;
  public static final int parena = 2;
  public static final int buscar = 35;
  public static final int filtrar = 34;
  public static final int menos = 8;
  public static final int var = 28;
  public static final int EOF = 0;
  public static final int pyc = 22;
  public static final int mas = 7;
  public static final int menorq = 13;
  public static final int error = 1;
  public static final int map = 36;
  public static final int or = 19;
  public static final int valor_nulo = 58;
  public static final int pot = 11;
  public static final int por = 9;
  public static final int punto = 25;
  public static final int mayorigualq = 14;
  public static final int dospuntos = 26;
  public static final int invertir = 31;
  public static final int caso = 44;
  public static final int valor_numero_decimal = 57;
  public static final int minimo = 33;
  public static final int menorigualq = 15;
  public static final int valor_cadena = 53;
  public static final int valor_simbolo = 56;
  public static final int todos = 38;
  public static final int diferente = 17;
  public static final int and = 18;
  public static final int not = 20;
  public static final int signoi = 27;
  public static final int descendente = 29;
  public static final int retornar = 46;
  public static final int div = 10;
  public static final int corchec = 24;
  public static final int valor_path2 = 52;
  public static final int selecciona = 47;
  public static final int corchea = 23;
  public static final int sino = 43;
}

