
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 19 17:00:41 CST 2019
//----------------------------------------------------

package Analizadores.GramaticaFS;

/** CUP generated class containing symbol constants. */
public class simbolofs {
  /* terminals */
  public static final int mayorq = 14;
  public static final int menorigualq = 17;
  public static final int valor_verdadero = 28;
  public static final int valor_simbolo = 30;
  public static final int not = 22;
  public static final int valor_numero_decimal = 31;
  public static final int pot = 11;
  public static final int valor_falso = 29;
  public static final int por = 9;
  public static final int valor_numero_completo = 24;
  public static final int or = 21;
  public static final int valor_path2 = 26;
  public static final int menos = 8;
  public static final int valor_id = 23;
  public static final int div = 10;
  public static final int igual = 6;
  public static final int incremento = 12;
  public static final int EOF = 0;
  public static final int decremento = 13;
  public static final int error = 1;
  public static final int mayorigualq = 16;
  public static final int parenc = 3;
  public static final int valor_nulo = 33;
  public static final int parena = 2;
  public static final int diferente = 19;
  public static final int mas = 7;
  public static final int llavec = 5;
  public static final int menorq = 15;
  public static final int valor_cadena = 27;
  public static final int llavea = 4;
  public static final int valor_path = 25;
  public static final int igualigual = 18;
  public static final int valor_caracter = 32;
  public static final int and = 20;
}

