
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 18 22:54:35 CST 2019
//----------------------------------------------------

package Analizadores.GramaticaGDATO;

/** CUP generated class containing symbol constants. */
public class simbologdato {
  /* terminals */
  public static final int div = 6;
  public static final int valor_numero_completo = 8;
  public static final int EOF = 0;
  public static final int lista = 5;
  public static final int principal = 4;
  public static final int error = 1;
  public static final int valor_cadena = 9;
  public static final int cierra = 3;
  public static final int valor_numero_decimal = 10;
  public static final int abre = 2;
  public static final int valor_id = 7;
}

