
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 14 17:41:16 CST 2019
//----------------------------------------------------

package Analizadores.GramaticaGXML;

/** CUP generated class containing symbol constants. */
public class simbolo {
  /* terminals */
  public static final int ancho = 19;
  public static final int comentario_multiple = 39;
  public static final int maximo = 26;
  public static final int auto_reproduccion = 29;
  public static final int e_multimedia = 10;
  public static final int e_texto = 5;
  public static final int e_contenedor = 4;
  public static final int mayorq = 30;
  public static final int valor_path = 37;
  public static final int igual = 33;
  public static final int e_boton = 11;
  public static final int valor_numero_completo = 36;
  public static final int e_ventana = 3;
  public static final int alto = 18;
  public static final int valor_id = 35;
  public static final int comentario_simple = 38;
  public static final int fuente = 22;
  public static final int EOF = 0;
  public static final int comilladoble = 34;
  public static final int menorq = 31;
  public static final int nombre = 21;
  public static final int error = 1;
  public static final int color = 15;
  public static final int e_enviar = 12;
  public static final int id = 13;
  public static final int y = 17;
  public static final int x = 16;
  public static final int tipo = 14;
  public static final int tam = 23;
  public static final int minimo = 27;
  public static final int path = 28;
  public static final int borde = 20;
  public static final int e_importar = 2;
  public static final int e_defecto = 7;
  public static final int div = 32;
  public static final int e_dato = 9;
  public static final int e_control = 6;
  public static final int cursiva = 25;
  public static final int negrita = 24;
  public static final int e_listadatos = 8;
}

