
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 17 18:58:21 CST 2019
//----------------------------------------------------

package Analizadores.GramaticaGXML;

/** CUP generated class containing symbol constants. */
public class simbolo {
  /* terminals */
  public static final int igualigual = 54;
  public static final int accionfinal = 34;
  public static final int ancho = 19;
  public static final int maximo = 26;
  public static final int auto_reproduccion = 29;
  public static final int accion = 32;
  public static final int e_multimedia = 10;
  public static final int e_texto = 5;
  public static final int e_contenedor = 4;
  public static final int mayorq = 50;
  public static final int valor_path = 61;
  public static final int coma = 45;
  public static final int igual = 39;
  public static final int abre = 36;
  public static final int e_boton = 11;
  public static final int valor_numero_completo = 60;
  public static final int e_ventana = 3;
  public static final int accioninicial = 33;
  public static final int alto = 18;
  public static final int valor_id = 59;
  public static final int llavec = 42;
  public static final int llavea = 41;
  public static final int valor_falso = 65;
  public static final int cierra = 37;
  public static final int parenc = 44;
  public static final int fuente = 22;
  public static final int valor_verdadero = 64;
  public static final int parena = 43;
  public static final int menos = 47;
  public static final int EOF = 0;
  public static final int mas = 46;
  public static final int comilladoble = 40;
  public static final int menorq = 51;
  public static final int nombre = 21;
  public static final int referencia = 35;
  public static final int error = 1;
  public static final int color = 15;
  public static final int or = 56;
  public static final int e_enviar = 12;
  public static final int por = 48;
  public static final int mayorigualq = 52;
  public static final int potencia = 49;
  public static final int id = 13;
  public static final int secundaria = 31;
  public static final int y = 17;
  public static final int x = 16;
  public static final int tipo = 14;
  public static final int tam = 23;
  public static final int menorigualq = 53;
  public static final int minimo = 27;
  public static final int valor_cadena = 63;
  public static final int path = 28;
  public static final int diferente = 55;
  public static final int not = 58;
  public static final int and = 57;
  public static final int borde = 20;
  public static final int e_importar = 2;
  public static final int e_defecto = 7;
  public static final int div = 38;
  public static final int e_dato = 9;
  public static final int principal = 30;
  public static final int valor_path2 = 62;
  public static final int e_control = 6;
  public static final int cursiva = 25;
  public static final int negrita = 24;
  public static final int e_listadatos = 8;
}

