
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 09 04:07:47 CST 2019
//----------------------------------------------------

package Analizadores.GramaticaGXML;

/** CUP generated class containing symbol constants. */
public class simbolo {
  /* terminals */
  public static final int e_dato = 9;
  public static final int menos = 51;
  public static final int ancho = 19;
  public static final int tam = 23;
  public static final int e_importar = 2;
  public static final int salto = 49;
  public static final int musica = 25;
  public static final int borde = 20;
  public static final int negrita = 27;
  public static final int valor_id = 67;
  public static final int accionfinal = 36;
  public static final int cursiva = 28;
  public static final int accion = 38;
  public static final int imagen = 26;
  public static final int valor_cadena = 73;
  public static final int referencia = 37;
  public static final int div = 41;
  public static final int secundaria = 34;
  public static final int mas = 50;
  public static final int dospuntos = 63;
  public static final int color = 15;
  public static final int e_ventana = 3;
  public static final int menorq = 55;
  public static final int maximo = 29;
  public static final int valor_numero_completo = 68;
  public static final int mayorq = 54;
  public static final int pyc = 64;
  public static final int accioninicial = 35;
  public static final int principal = 33;
  public static final int menorigualq = 57;
  public static final int auto_reproduccion = 32;
  public static final int e_texto = 5;
  public static final int y = 17;
  public static final int x = 16;
  public static final int valor_simbolo = 76;
  public static final int or = 60;
  public static final int mayorigualq = 56;
  public static final int video = 24;
  public static final int valor_verdadero = 74;
  public static final int llavec = 45;
  public static final int llavea = 44;
  public static final int abre = 39;
  public static final int id = 13;
  public static final int e_control = 6;
  public static final int valor_path4 = 72;
  public static final int valor_path3 = 71;
  public static final int valor_path2 = 70;
  public static final int path = 31;
  public static final int valor_falso = 75;
  public static final int e_defecto = 7;
  public static final int minimo = 30;
  public static final int comilladoble = 43;
  public static final int e_listadatos = 8;
  public static final int and = 61;
  public static final int e_multimedia = 10;
  public static final int e_contenedor = 4;
  public static final int parenc = 47;
  public static final int EOF = 0;
  public static final int parena = 46;
  public static final int e_enviar = 12;
  public static final int fuente = 22;
  public static final int cierra = 40;
  public static final int potencia = 53;
  public static final int alto = 18;
  public static final int error = 1;
  public static final int diferente = 59;
  public static final int igualigual = 58;
  public static final int por = 52;
  public static final int valor_path = 69;
  public static final int interrogac = 66;
  public static final int interrogaa = 65;
  public static final int coma = 48;
  public static final int not = 62;
  public static final int igual = 42;
  public static final int e_boton = 11;
  public static final int tipo = 14;
  public static final int nombre = 21;
}

